/** @file events.cpp
 * @brief Stores the event texts and modifiers.
 */
#include "events.h"
#include <iostream>
#include <algorithm>

/** @brief The list of all events that can be applied to the stocks.
 * @ref category_list
 * @details
 * | Event ID Range | Affected Category |
 * | -------------- | ----------------- |
 * | 0 to 8         | All Stocks        |
 * | 9 to 17        | Adv&Market        |
 * | 18 to 31       | Aero&Def          |
 * | 32 to 49       | Airlines          |
 * | 50 to 62       | RenewEnergy       |
 * | 63 to 72       | Auto              |
 * | 73 to 81       | Banks             |
 * | 82 to 91       | Biotech           |
 * | 92 to 94       | Broadcast         |
 * | 95 to 110      | Casinos&Gaming    |
 * | 111 to 122     | E-Commerce        |
 * | 123 to 130     | FinServices       |
 * | 131 to 145     | Food&Beverage     |
 * | 146 to 160     | Healthcare        |
 * | 161 to 175     | Tech              |
 * | 176 to 187     | RealEstate        |
 * | 188 to 193     | Retail            |
 * | 194 to 201     | Telecom           |
 * | 202 to 209     | pick_random_stock |
 */
std::vector<Stock_event> all_stock_events = {
    // event_id 0 to 8 affect all stocks
    {/** event_id */ 0,
     /** mutually_exclusive_events */ {1},
     /** text */ "The FED has decreased the interest rate!",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ all_stocks,
     /** category */ 0,
     /** modifiers*/ {{standard_deviation, 0.1}, {mean, 2}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 1,
     /** mutually_exclusive_events */ {0, 3},
     /** text */ "The FED has increased the interest rate!",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ all_stocks,
     /** category */ 0,
     /** modifiers*/ {{standard_deviation, 0.1}, {mean, -2}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 2,
     /** mutually_exclusive_events */ {},
     /** text */ "Economic Recession: Market Downturn Signals Investor Concerns",
     /** duration */ 7,
     /** percentage_permille */ 20,
     /** type_of_event */ all_stocks,
     /** category */ 0,
     /** modifiers*/ {{standard_deviation, 0.2}, {mean, -5}, {lower_limit, -50}, {upper_limit, 0}}},
    {/** event_id */ 3,
     /** mutually_exclusive_events */ {1},
     /** text */ "Central Bank Cuts Interest Rates: Market Stimulus Boosts Investor Sentiment",
     /** duration */ 3,
     /** percentage_permille */ 5,
     /** type_of_event */ all_stocks,
     /** category */ 0,
     /** modifiers*/ {{standard_deviation, 0.05}, {mean, 1}, {lower_limit, 0}, {upper_limit, 10}}},
    {/** event_id */ 4,
     /** mutually_exclusive_events */ {},
     /** text */ "Trade War Escalates: Global Market Volatility Amidst Rising Tensions",
     /** duration */ 5,
     /** percentage_permille */ 15,
     /** type_of_event */ all_stocks,
     /** category */ 0,
     /** modifiers*/ {{standard_deviation, 0.15}, {mean, -3}, {lower_limit, -30}, {upper_limit, 0}}},
    {/** event_id */ 5,
     /** mutually_exclusive_events */ {},
     /** text */ "Natural Disaster Strikes: Stock Market Reacts to Catastrophic Event",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ all_stocks,
     /** category */ 0,
     /** modifiers*/ {{standard_deviation, 0.1}, {mean, -2}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 6,
     /** mutually_exclusive_events */ {},
     /** text */ "Government Policy Change: Market Impacted by New Regulations",
     /** duration */ 4,
     /** percentage_permille */ 8,
     /** type_of_event */ all_stocks,
     /** category */ 0,
     /** modifiers*/ {{standard_deviation, 0.08}, {mean, -1}, {lower_limit, -15}, {upper_limit, 5}}},
    {/** event_id */ 7,
     /** mutually_exclusive_events */ {},
     /** text */ "Inflation Surges: Market Concerns Rise as Prices Soar",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ all_stocks,
     /** category */ 0,
     /** modifiers*/ {{standard_deviation, 0.12}, {mean, 0}, {lower_limit, -25}, {upper_limit, 0}}},
    {/** event_id */ 8,
     /** mutually_exclusive_events */ {},
     /** text */ "The US Dollar Plummets: Investors Raise Concern as International Trade Affected",
     /** duration */ 5,
     /** percentage_permille */ 5,
     /** type_of_event */ all_stocks,
     /** category */ 0,
     /** modifiers*/ {{standard_deviation, 0.1}, {mean, -3}, {lower_limit, -25}, {upper_limit, 0}}},
    // event_id 9 to 17 affect category "Adv&Market"
    {/** event_id */ 9,
     /** mutually_exclusive_events */ {},
     /** text */ "New Social Media Platform Disrupts Advertising Landscape",
     /** duration */ 4,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, -3}, {lower_limit, -10}, {upper_limit, 0}}},
    {/** event_id */ 10,
     /** mutually_exclusive_events */ {},
     /** text */ "Digital Advertising Spend Reaches All-Time High",
     /** duration */ 6,
     /** percentage_permille */ 15,
     /** type_of_event */ category,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 5}, {lower_limit, 0}, {upper_limit, 30}}},
    {/** event_id */ 11,
     /** mutually_exclusive_events */ {},
     /** text */ "Marketing Automation Tools Gain Popularity Among Businesses",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, 2}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 12,
     /** mutually_exclusive_events */ {},
     /** text */ "Two Media Platforms Cooperate: Doodle and Petaverse Exchanges User Data",
     /** duration */ 5,
     /** percentage_permille */ 7,
     /** type_of_event */ category,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.09}, {mean, 3}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 13,
     /** mutually_exclusive_events */ {},
     /** text */ "Artificial Intelligence Revolutionizes Targeted Advertising",
     /** duration */ 5,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 4}, {lower_limit, 0}, {upper_limit, 25}}},
    {/** event_id */ 14,
     /** mutually_exclusive_events */ {},
     /** text */ "Large Marketing Data Breach: Scams and Spams More Prominent",
     /** duration */ 5,
     /** percentage_permille */ 6,
     /** type_of_event */ category,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, -1}, {lower_limit, -15}, {upper_limit, 5}}},
    {/** event_id */ 15,
     /** mutually_exclusive_events */ {},
     /** text */ "Civilian Protests Against Anti-Adblock Measures Expand",
     /** duration */ 5,
     /** percentage_permille */ 11,
     /** type_of_event */ category,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, -2}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 16,
     /** mutually_exclusive_events */ {},
     /** text */ "Advertising Revenue Affected as More Users Resort to Piracy",
     /** duration */ 5,
     /** percentage_permille */ 9,
     /** type_of_event */ category,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.04}, {mean, -1}, {lower_limit, -10}, {upper_limit, 0}}},
    {/** event_id */ 17,
     /** mutually_exclusive_events */ {},
     /** text */ "Advertisers Gain Access to Government Surveillence Data",
     /** duration */ 5,
     /** percentage_permille */ 9,
     /** type_of_event */ category,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.17}, {mean, 3}, {lower_limit, -5}, {upper_limit, 20}}},
    // event_id 18 to 31 affect category "Aero&Def"
    {/** event_id */ 18,
     /** mutually_exclusive_events */ {19},
     /** text */ "Government Increases Defense Spending Amid Rising Geopolitical Tensions",
     /** duration */ 4,
     /** percentage_permille */ 5,
     /** type_of_event */ category,
     /** category */ 1,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 5}, {lower_limit, 0}, {upper_limit, 30}}},
    {/** event_id */ 19,
     /** mutually_exclusive_events */ {18},
     /** text */ "Emerging Technologies Transform Aerospace Industry",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 1,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, 3}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 20,
     /** mutually_exclusive_events */ {},
     /** text */ "Space Exploration Companies Achieve Major Milestones",
     /** duration */ 5,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 1,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, 2}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 21,
     /** mutually_exclusive_events */ {22},
     /** text */ "Supply Chain Disruptions Hinder Aerospace Manufacturing",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 1,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, -3}, {lower_limit, -10}, {upper_limit, 0}}},
    {/** event_id */ 22,
     /** mutually_exclusive_events */ {21},
     /** text */ "Budget Cuts Lead to Decreased Defense Contracts",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 1,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -2}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 23,
     /** mutually_exclusive_events */ {},
     /** text */ "President of Merica Declares National Emergency, Rivals Speculating Possible Civil War",
     /** duration */ 6,
     /** percentage_permille */ 3,
     /** type_of_event */ category,
     /** category */ 1,
     /** modifiers */ {{standard_deviation, 0.19}, {mean, 4}, {lower_limit, -10}, {upper_limit, 25}}},
    {/** event_id */ 24,
     /** mutually_exclusive_events */ {},
     /** text */ "Scientists Feasiblised Development of Mars for Human Residence",
     /** duration */ 7,
     /** percentage_permille */ 7,
     /** type_of_event */ category,
     /** category */ 1,
     /** modifiers */ {{standard_deviation, 0.09}, {mean, 5}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 25,
     /** mutually_exclusive_events */ {},
     /** text */ "Telescope Hubble II Reveals First Detailed Photograph of a Planet Outside Solar System",
     /** duration */ 4,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 1,
     /** modifiers */ {{standard_deviation, 0.13}, {mean, 4}, {lower_limit, 0}, {upper_limit, 17}}},
    {/** event_id */ 26,
     /** mutually_exclusive_events */ {},
     /** text */ "President of North Borea Dies, South Borea Suspected For Asssassination",
     /** duration */ 4,
     /** percentage_permille */ 2,
     /** type_of_event */ category,
     /** category */ 1,
     /** modifiers */ {{standard_deviation, 0.23}, {mean, 3}, {lower_limit, -20}, {upper_limit, 25}}},
    {/** event_id */ 27,
     /** mutually_exclusive_events */ {},
     /** text */ "Haiwan Surrenders to Chino After War, Teijing Triumphs for the Reunification of the Country",
     /** duration */ 3,
     /** percentage_permille */ 5,
     /** type_of_event */ category,
     /** category */ 1,
     /** modifiers */ {{standard_deviation, 0.18}, {mean, 3}, {lower_limit, -11}, {upper_limit, 19}}},
    {/** event_id */ 28,
     /** mutually_exclusive_events */ {},
     /** text */ "Neutron Bomb Test Suceeded, About As Powerful As Hydrogen Bomb",
     /** duration */ 6,
     /** percentage_permille */ 3,
     /** type_of_event */ category,
     /** category */ 1,
     /** modifiers */ {{standard_deviation, 0.18}, {mean, 5}, {lower_limit, -1}, {upper_limit, 20}}},
    {/** event_id */ 29,
     /** mutually_exclusive_events */ {},
     /** text */ "Commercial Space Travel Reaches the Moon",
     /** duration */ 8,
     /** percentage_permille */ 9,
     /** type_of_event */ category,
     /** category */ 1,
     /** modifiers */ {{standard_deviation, 0.14}, {mean, 3}, {lower_limit, 0}, {upper_limit, 18}}},
    {/** event_id */ 30,
     /** mutually_exclusive_events */ {},
     /** text */ "Satalite Communication Phases Out Traditional",
     /** duration */ 10,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 1,
     /** modifiers */ {{standard_deviation, 0.17}, {mean, 4}, {lower_limit, 0}, {upper_limit, 21}}},
    {/** event_id */ 31,
     /** mutually_exclusive_events */ {},
     /** text */ "USSR Comes Back To Life as Bussia Controls Wukarine, Merica Prepares for War",
     /** duration */ 7,
     /** percentage_permille */ 4,
     /** type_of_event */ category,
     /** category */ 1,
     /** modifiers */ {{standard_deviation, 0.21}, {mean, 2}, {lower_limit, -17}, {upper_limit, 21}}},
    // event_id 32 to 49 affect category "Airlines"
    {/** event_id */ 32,
     /** mutually_exclusive_events */ {},
     /** text */ "Airline Industry Experiences Surge in Travel Demand",
     /** duration */ 7,
     /** percentage_permille */ 15,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 5}, {lower_limit, 0}, {upper_limit, 30}}},
    {/** event_id */ 33,
     /** mutually_exclusive_events */ {},
     /** text */ "Fuel Prices Skyrocket, Putting Pressure on Airlines' Profit Margins",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, -3}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 34,
     /** mutually_exclusive_events */ {},
     /** text */ "Airline Strikes Disrupt Travel Plans for Thousands of Passengers",
     /** duration */ 5,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -2}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 35,
     /** mutually_exclusive_events */ {},
     /** text */ "New Low-Cost Airline Enters the Market, Intensifying Competition",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 3}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 36,
     /** mutually_exclusive_events */ {},
     /** text */ "Natural Disasters Disrupt Airline Operations and Cause Flight Cancellations",
     /** duration */ 3,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -2}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 37,
     /** mutually_exclusive_events */ {},
     /** text */ "New Security Regulations Increase Operational Costs for Airlines",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, -1}, {lower_limit, -10}, {upper_limit, 0}}},
    {/** event_id */ 38,
     /** mutually_exclusive_events */ {},
     /** text */ "Airobus Announces Breakthrough in Electric Airplanes",
     /** duration */ 6
     /** percentage_permille */ 5,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.07}, {mean, 4}, {lower_limit, 0}, {upper_limit, 21}}},
    {/** event_id */ 39,
     /** mutually_exclusive_events */ {},
     /** text */ "Plane Crash Kills Hundreds, Engineers Arrested For Design Fault",
     /** duration */ 6
     /** percentage_permille */ 2,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.22}, {mean, -6}, {lower_limit, -22}, {upper_limit, 0}}},
    {/** event_id */ 40,
     /** mutually_exclusive_events */ {},
     /** text */ "Near Misses on Plane Crashes Spark Doubts in Safety",
     /** duration */ 6
     /** percentage_permille */ 9,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.11}, {mean, -2}, {lower_limit, -9}, {upper_limit, 0}}},
    {/** event_id */ 41,
     /** mutually_exclusive_events */ {},
     /** text */ "First International Sale of Chino-made Civil Plane",
     /** duration */ 6
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.11}, {mean, 2}, {lower_limit, 0}, {upper_limit, 12}}},
    {/** event_id */ 42,
     /** mutually_exclusive_events */ {43},
     /** text */ "Aircraft Manufacteur Boing Financial Report Shows Large Gains",
     /** duration */ 6
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.05}, {mean, 2}, {lower_limit, 0}, {upper_limit, 10}}},
    {/** event_id */ 43,
     /** mutually_exclusive_events */ {42},
     /** text */ "Aircraft Manufacteur Boing Financial Report Shows Large Losses",
     /** duration */ 6
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.05}, {mean, -2}, {lower_limit, -10}, {upper_limit, 0}}},
    {/** event_id */ 44,
     /** mutually_exclusive_events */ {},
     /** text */ "Flight Computer Faults Prompt Suspension of an Aircraft Model Globally",
     /** duration */ 6
     /** percentage_permille */ 9,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, -3}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 45,
     /** mutually_exclusive_events */ {},
     /** text */ "Intercontinential High Speed Railway Breakthroughs, Aviation Market Share may be Corroded",
     /** duration */ 6
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.13}, {mean, -2}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 46,
     /** mutually_exclusive_events */ {},
     /** text */ "VR Conference May Reduce The Need of Flying For Meetings",
     /** duration */ 6
     /** percentage_permille */ 9,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.05}, {mean, -2}, {lower_limit, -10}, {upper_limit, 0}}},
    {/** event_id */ 47,
     /** mutually_exclusive_events */ {},
     /** text */ "Global Pandemic Reduces Travel Demands",
     /** duration */ 6
     /** percentage_permille */ 5,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.09}, {mean, -3}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 48,
     /** mutually_exclusive_events */ {},
     /** text */ "Large Aircraft Developed With Capacity of 1000 People",
     /** duration */ 6
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 3}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 49,
     /** mutually_exclusive_events */ {},
     /** text */ "Terrorists Hijack Planes, Caused Hundred Deaths and Nearly Been Another 911",
     /** duration */ 6
     /** percentage_permille */ 2,
     /** type_of_event */ category,
     /** category */ 2,
     /** modifiers */ {{standard_deviation, 0.22}, {mean, -5}, {lower_limit, -30}, {upper_limit, 0}}},
    // event_id  50 to 62 affect category "RenewEnergy"
    {/** event_id */ 50,
     /** mutually_exclusive_events */ {53},
     /** text */ "Government Implements New Incentives to Promote Renewable Energy Adoption",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 3,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 3}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 51,
     /** mutually_exclusive_events */ {},
     /** text */ "Breakthrough in Solar Panel Technology Increases Efficiency by 20%",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 3,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, 2}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 52,
     /** mutually_exclusive_events */ {},
     /** text */ "Investment in Wind Farms Surges as Costs of Wind Energy Decrease",
     /** duration */ 7,
     /** percentage_permille */ 16,
     /** type_of_event */ category,
     /** category */ 3,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 5}, {lower_limit, 0}, {upper_limit, 30}}},
    {/** event_id */ 53,
     /** mutually_exclusive_events */ {50, 62},
     /** text */ "Government Cuts Subsidies for Renewable Energy Projects, Slowing Down Progress",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 3,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, -3}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 54,
     /** mutually_exclusive_events */ {},
     /** text */ "Persistent Cloud Cover Reduces Solar Power Generation",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 3,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, -2}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 55,
     /** mutually_exclusive_events */ {},
     /** text */ "Nuclear Fusion Breakthroughs, May Mean Practically Unlimited Energy Production in The Near Future",
     /** duration */ 5,
     /** percentage_permille */ 3,
     /** type_of_event */ category,
     /** category */ 3,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 8}, {lower_limit, 0}, {upper_limit, 40}}},
    {/** event_id */ 56,
     /** mutually_exclusive_events */ {},
     /** text */ "International Typhoon Destroyed Wind Turbines, Repair Expenses Increase",
     /** duration */ 5,
     /** percentage_permille */ 4,
     /** type_of_event */ category,
     /** category */ 3,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, -2}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 57,
     /** mutually_exclusive_events */ {},
     /** text */ "Multiple Countries Open Volcanoes For Geothermal Energy Generation",
     /** duration */ 5,
     /** percentage_permille */ 7,
     /** type_of_event */ category,
     /** category */ 3,
     /** modifiers */ {{standard_deviation, 0.09}, {mean, 2}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 58,
     /** mutually_exclusive_events */ {},
     /** text */ "Coal Banned From Industrial Use and Production, Industries May Switch to Renewables",
     /** duration */ 5,
     /** percentage_permille */ 7,
     /** type_of_event */ category,
     /** category */ 3,
     /** modifiers */ {{standard_deviation, 0.07}, {mean, 2}, {lower_limit, 0}, {upper_limit, 10}}},
    {/** event_id */ 59,
     /** mutually_exclusive_events */ {},
     /** text */ "Crude Oil Remaining In Crust Alarmingly Little, Industries May Switch to Renewables",
     /** duration */ 5,
     /** percentage_permille */ 5,
     /** type_of_event */ category,
     /** category */ 3,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, 2}, {lower_limit, 0}, {upper_limit, 10}}},
    {/** event_id */ 60,
     /** mutually_exclusive_events */ {},
     /** text */ "Solar Panels Built in Deserts Are Now Operating",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 3,
     /** modifiers */ {{standard_deviation, 0.09}, {mean, 3}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 61,
     /** mutually_exclusive_events */ {},
     /** text */ "More Farms Now Produce Energy From Biomass",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 3,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 2}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 62,
     /** mutually_exclusive_events */ {53},
     /** text */ "Government Started Subsidy To Build Solar Panels On Top Of Buildings",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 3,
     /** modifiers */ {{standard_deviation, 0.11}, {mean, 3}, {lower_limit, 0}, {upper_limit, 17}}},
    // event_id 63 to 72 affect category "Auto"
    {/** event_id */ 63,
     /** mutually_exclusive_events */ {},
     /** text */ "Breakthrough in Electric Vehicle Battery Technology Extends Range and Reduces Charging Time",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 4,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, 3}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 64,
     /** mutually_exclusive_events */ {},
     /** text */ "Sudden Increase in Oil Prices Impacts Affordability and Demand for Conventional Vehicles",
     /** duration */ 5,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 4,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, -2}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 65,
     /** mutually_exclusive_events */ {66},
     /** text */ "Introduction of Advanced Driver Assistance Systems Enhances Vehicle Safety",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 4,
     /** modifiers */ {{standard_deviation, 0.06}, {mean, 2}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 66,
     /** mutually_exclusive_events */ {65},
     /** text */ "Frequent Accidents raise safety Concerns",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 4,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, -5}, {lower_limit, -30}, {upper_limit, 0}}},
    {/** event_id */ 67,
     /** mutually_exclusive_events */ {68, 69},
     /** text */ "Taxes Raise For Vehicles",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 4,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, -3}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 68,
     /** mutually_exclusive_events */ {67, 69},
     /** text */ "Taxes Fall For Vehicles",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 4,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 3}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 69,
     /** mutually_exclusive_events */ {67, 68},
     /** text */ "Taxes Fall For Electric Vehicles but Raise For Traditional Vechicles",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 4,
     /** modifiers */ {{standard_deviation, 0.16}, {mean, 0}, {lower_limit, -10}, {upper_limit, +10}}},
    {/** event_id */ 70,
     /** mutually_exclusive_events */ {},
     /** text */ "Expansion of Public Transport Hurts Personal Vehicle Demands",
     /** duration */ 6,
     /** percentage_permille */ 9,
     /** type_of_event */ category,
     /** category */ 4,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, -3}, {lower_limit, -25}, {upper_limit, 0}}},
    {/** event_id */ 71,
     /** mutually_exclusive_events */ {},
     /** text */ "More People Switch to Self Driving Cars",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 4,
     /** modifiers */ {{standard_deviation, 0.07}, {mean, 2}, {lower_limit, 0}, {upper_limit, 10}}},
    {/** event_id */ 72,
     /** mutually_exclusive_events */ {},
     /** text */ "Government Fixes and Improved Road Condition",
     /** duration */ 6,
     /** percentage_permille */ 11,
     /** type_of_event */ category,
     /** category */ 4,
     /** modifiers */ {{standard_deviation, 0.06}, {mean, 1}, {lower_limit, 0}, {upper_limit, 0}}},
    // event_id 73 to 81 affect category "Banks"
    {/** event_id */ 73,
     /** mutually_exclusive_events */ {},
     /** text */ "Economic Recession Triggers Increase in Non-Performing Loans, Putting Banks at Risk",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 5,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, -4}, {lower_limit, -25}, {upper_limit, 0}}},
    {/** event_id */ 74,
     /** mutually_exclusive_events */ {},
     /** text */ "Government Introduces Stimulus Package to Boost Lending and Economic Growth",
     /** duration */ 6,
     /** percentage_permille */ 15,
     /** type_of_event */ category,
     /** category */ 5,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, 5}, {lower_limit, 0}, {upper_limit, 25}}},
    {/** event_id */ 75,
     /** mutually_exclusive_events */ {},
     /** text */ "Government Implements Excessive Money Printing, Leading to Inflation and Currency Devaluation",
     /** duration */ 8,
     /** percentage_permille */ 16,
     /** type_of_event */ category,
     /** category */ 5,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, 0}, {lower_limit, -40}, {upper_limit, 0}}},
    {/** event_id */ 76,
     /** mutually_exclusive_events */ {},
     /** text */ "A Bank Run In ABC Bank Causes Lack Of Trust In Those Remaining",
     /** duration */ 8,
     /** percentage_permille */ 3,
     /** type_of_event */ category,
     /** category */ 5,
     /** modifiers */ {{standard_deviation, 0.13}, {mean, -8}, {lower_limit, -40}, {upper_limit, 0}}},
    {/** event_id */ 77,
     /** mutually_exclusive_events */ {},
     /** text */ "Multiple Industries Are Saturated and Companies Lend Less",
     /** duration */ 8,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 5,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, -3}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 78,
     /** mutually_exclusive_events */ {},
     /** text */ "Instant Sucess Of International Companies Prompted Founding Of Many Start-ups which borrow to start",
     /** duration */ 8,
     /** percentage_permille */ 14,
     /** type_of_event */ category,
     /** category */ 5,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 3}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 79,
     /** mutually_exclusive_events */ {},
     /** text */ "Online Banking Grows, Bringing More Convenience",
     /** duration */ 8,
     /** percentage_permille */ 13,
     /** type_of_event */ category,
     /** category */ 5,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 2}, {lower_limit, 0}, {upper_limit, 10}}},
    {/** event_id */ 80,
     /** mutually_exclusive_events */ {81},
     /** text */ "Investment Products Face Losses",
     /** duration */ 8,
     /** percentage_permille */ 16,
     /** type_of_event */ category,
     /** category */ 5,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, -3}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 81,
     /** mutually_exclusive_events */ {80},
     /** text */ "Investment Products Accumulate Gains",
     /** duration */ 8,
     /** percentage_permille */ 16,
     /** type_of_event */ category,
     /** category */ 5,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 3}, {lower_limit, 0}, {upper_limit, 15}}},
    // event_id 82 to 91 affect category "Biotech"
    {/** event_id */ 82,
     /** mutually_exclusive_events */ {},
     /** text */ "Breakthrough in Gene Therapy Offers Potential Cure for Genetic Diseases",
     /** duration */ 7,
     /** percentage_permille */ 14,
     /** type_of_event */ category,
     /** category */ 6,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 4}, {lower_limit, 0}, {upper_limit, 25}}},
    {/** event_id */ 83,
     /** mutually_exclusive_events */ {},
     /** text */ "Clinical Trial Failure Delays Development of Promising Drug Candidate",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 6,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, -3}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 84,
     /** mutually_exclusive_events */ {},
     /** text */ "Successful FDA Approval Expedites Commercialization of Innovative Biotech Products",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 6,
     /** modifiers */ {{standard_deviation, 0.09}, {mean, 3}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 85,
     /** mutually_exclusive_events */ {},
     /** text */ "Scientists Come Up With New Medicine For Cancer Without Damage To Patient",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 6,
     /** modifiers */ {{standard_deviation, 0.07}, {mean, 3}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 86,
     /** mutually_exclusive_events */ {},
     /** text */ "A Lab Has Leaked And Harmful Bacteria Escaped",
     /** duration */ 6,
     /** percentage_permille */ 3,
     /** type_of_event */ category,
     /** category */ 6,
     /** modifiers */ {{standard_deviation, 0.09}, {mean, -4}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 87,
     /** mutually_exclusive_events */ {},
     /** text */ "First Patient Fully Recovered After Transplant of Animal-Grown Human Organs",
     /** duration */ 6,
     /** percentage_permille */ 11,
     /** type_of_event */ category,
     /** category */ 6,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, 4}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 88,
     /** mutually_exclusive_events */ {},
     /** text */ "Common Flu Has Been Eliminated By New Medicine",
     /** duration */ 6,
     /** percentage_permille */ 7,
     /** type_of_event */ category,
     /** category */ 6,
     /** modifiers */ {{standard_deviation, 0.09}, {mean, 3}, {lower_limit, 0}, {upper_limit, 25}}},
    {/** event_id */ 89,
     /** mutually_exclusive_events */ {},
     /** text */ "Journalists Criticise Cutting Edge Medical Development Being Unavailable To The Poor",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 6,
     /** modifiers */ {{standard_deviation, 0.07}, {mean, -1}, {lower_limit, 0}, {upper_limit, 0}}},
    {/** event_id */ 90,
     /** mutually_exclusive_events */ {},
     /** text */ "Methods To Slow Aging Has Been Discovered",
     /** duration */ 6,
     /** percentage_permille */ 5,
     /** type_of_event */ category,
     /** category */ 6,
     /** modifiers */ {{standard_deviation, 0.09}, {mean, 4}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 91,
     /** mutually_exclusive_events */ {},
     /** text */ "Medical Development Plateus As Developments Encounter Ethical Issues",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 6,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, -2}, {lower_limit, -20}, {upper_limit, 0}}},
    // event_id 92 to 94 affect category "Broadcast"
    {/** event_id */ 92,
     /** mutually_exclusive_events */ {},
     /** text */ "New Streaming Service Launches with Extensive Content Library and Innovative Features",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 7,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, 3}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 93,
     /** mutually_exclusive_events */ {},
     /** text */ "Broadcast Network Faces Significant Revenue Losses Due to Declining Viewership",
     /** duration */ 7,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 7,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, -4}, {lower_limit, -25}, {upper_limit, 0}}},
    {/** event_id */ 94,
     /** mutually_exclusive_events */ {},
     /** text */ "Broadcast Network Strikes Exclusive Deal for Live Coverage of Major Sporting Event",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 7,
     /** modifiers */ {{standard_deviation, 0.07}, {mean, 2}, {lower_limit, 0}, {upper_limit, 15}}},
    // event_id 95 to 110 affect category "Casinos&Gaming"
    {/** event_id */ 95,
     /** mutually_exclusive_events */ {},
     /** text */ "Stringent Gambling Regulations Restrict Casino Operations",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.10}, {mean, -4}, {lower_limit, -25}, {upper_limit, 0}}},
    {/** event_id */ 96,
     /** mutually_exclusive_events */ {},
     /** text */ "Innovative Strategies Help Casinos Navigate Stringent Regulations and Minimize Revenue Losses",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.08}, {mean, 3}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 97,
     /** mutually_exclusive_events */ {45},
     /** text */ "Online Gaming Goes Viral, Attracting Millions of Players Worldwide",
     /** duration */ 5,
     /** percentage_permille */ 20,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 5}, {lower_limit, 0}, {upper_limit, 30}}},
    {/** event_id */ 98,
     /** mutually_exclusive_events */ {},
     /** text */ "New Esports Tournament Breaks Viewership Records",
     /** duration */ 4,
     /** percentage_permille */ 15,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 7}, {lower_limit, 0}, {upper_limit, 25}}},
    {/** event_id */ 99,
     /** mutually_exclusive_events */ {43},
     /** text */ "Major Data Breach Affects Gaming Platforms, Raising Concerns About Player Privacy",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -4}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 100,
     /** mutually_exclusive_events */ {},
     /** text */ "Introduction of Virtual Reality Gaming Enhances Player Immersion and Experience",
     /** duration */ 5,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 101,
     /** mutually_exclusive_events */ {},
     /** text */ "Teenagers Banned From Computer Games On Weekdays",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.13}, {mean, -10}, {lower_limit, -50}, {upper_limit, 0}}},
    {/** event_id */ 102,
     /** mutually_exclusive_events */ {},
     /** text */ "Crypto Mining Reduces Graphics Card Availability To Gamers",
     /** duration */ 5,
     /** percentage_permille */ 14,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -3}, {lower_limit, -10}, {upper_limit, 0}}},
    {/** event_id */ 103,
     /** mutually_exclusive_events */ {},
     /** text */ "Founder Of A Chain Casino Arrested For Bribery",
     /** duration */ 5,
     /** percentage_permille */ 9,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -2}, {lower_limit, -5}, {upper_limit, 0}}},
    {/** event_id */ 104,
     /** mutually_exclusive_events */ {},
     /** text */ "Top Game Streamer Dies Of Cancer, Players Mourn",
     /** duration */ 5,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.19}, {mean, 0}, {lower_limit, -10}, {upper_limit, 10}}},
    {/** event_id */ 105,
     /** mutually_exclusive_events */ {},
     /** text */ "Major Game Console Manufacteur Goes Out Of Business",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 106,
     /** mutually_exclusive_events */ {},
     /** text */ "Gaming Was Used To Help Brain Disease Patients Recover",
     /** duration */ 5,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.13}, {mean, 3}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 107,
     /** mutually_exclusive_events */ {},
     /** text */ "Researchers Find No Evidence Those Who Game Learn Worse Contrary To Common Belief",
     /** duration */ 5,
     /** percentage_permille */ 11,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.11}, {mean, 2}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 108,
     /** mutually_exclusive_events */ {},
     /** text */ "New Game Goes Viral Thanks To Memes",
     /** duration */ 5,
     /** percentage_permille */ 14,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 4}, {lower_limit, 0}, {upper_limit, 24}}},
    {/** event_id */ 109,
     /** mutually_exclusive_events */ {},
     /** text */ "Price Increases In Gaming Consoles Reduces Purchases",
     /** duration */ 5,
     /** percentage_permille */ 13,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -1}, {lower_limit, -10}, {upper_limit, 0}}},
    {/** event_id */ 110,
     /** mutually_exclusive_events */ {},
     /** text */ "Multiple Games Remove Support For Aging Computers",
     /** duration */ 5,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 8,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -1}, {lower_limit, 0}, {upper_limit, 0}}},
    // event_id 111 to 122 affect category "E-Commerce"
    {/** event_id */ 111,
     /** mutually_exclusive_events */ {},
     /** text */ "E-commerce Sales Reach All-Time High, Exceeding Market Expectations",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 9,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 112,
     /** mutually_exclusive_events */ {},
     /** text */ "Supply Chain Disruptions Cause Delivery Delays and Inventory Shortages in E-commerce",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 9,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -4}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 113,
     /** mutually_exclusive_events */ {},
     /** text */ "Introduction of Innovative Payment Solutions Boosts E-commerce Conversion Rates",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 9,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 4}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 114,
     /** mutually_exclusive_events */ {},
     /** text */ "Cybersecurity Breach Raises Concerns About Online Shopping Privacy and Data Protection",
     /** duration */ 6,
     /** percentage_permille */ 15,
     /** type_of_event */ category,
     /** category */ 9,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -7}, {lower_limit, -25}, {upper_limit, 0}}},
    {/** event_id */ 115,
     /** mutually_exclusive_events */ {},
     /** text */ "Advancements in Artificial Intelligence Revolutionize Personalized Shopping Experiences",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 9,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 5}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 116,
     /** mutually_exclusive_events */ {},
     /** text */ "Increase In Shop Rent Forces More To Adapt To Online Shopping",
     /** duration */ 5,
     /** percentage_permille */ 11,
     /** type_of_event */ category,
     /** category */ 9,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 3}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 117,
     /** mutually_exclusive_events */ {},
     /** text */ "Discounts In Offline Shops Attempts Regaining Market From Online Shops",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 9,
     /** modifiers */ {{standard_deviation, 0.17}, {mean, -2}, {lower_limit, -10}, {upper_limit, 0}}},
    {/** event_id */ 118,
     /** mutually_exclusive_events */ {},
     /** text */ "New Online Shopping Platform Disrupts Market With Discounts",
     /** duration */ 5,
     /** percentage_permille */ 11,
     /** type_of_event */ category,
     /** category */ 9,
     /** modifiers */ {{standard_deviation, 0.21}, {mean, 1}, {lower_limit, 0}, {upper_limit, 10}}},
    {/** event_id */ 119,
     /** mutually_exclusive_events */ {},
     /** text */ "Explosion In Shipping Company Destroys Thousands Of Packages",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 9,
     /** modifiers */ {{standard_deviation, 0.13}, {mean, -1}, {lower_limit, -5}, {upper_limit, 0}}},
    {/** event_id */ 120,
     /** mutually_exclusive_events */ {},
     /** text */ "Renowned Online Shopping Platform Apologises For Frequent Scams By Malicious Sellers",
     /** duration */ 5,
     /** percentage_permille */ 9,
     /** type_of_event */ category,
     /** category */ 9,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -3}, {lower_limit, -24}, {upper_limit, 0}}},
    {/** event_id */ 121,
     /** mutually_exclusive_events */ {},
     /** text */ "",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 9,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 5}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 122,
     /** mutually_exclusive_events */ {},
     /** text */ "Police Cracks Down On Multiple Scamming Websites Which Pretend To Be Common Online Shopping Sites",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 9,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 2}, {lower_limit, 0}, {upper_limit, 10}}},
    // event_id 123 to 130 affect category "FinServices"
    {/** event_id */ 123,
     /** mutually_exclusive_events */ {124},
     /** text */ "Fintech Startups Disrupt Traditional Banking, Providing Innovative Financial Services",
     /** duration */ 6,
     /** percentage_permille */ 15,
     /** type_of_event */ category,
     /** category */ 10,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 7}, {lower_limit, 0}, {upper_limit, 25}}},
    {/** event_id */ 124,
     /** mutually_exclusive_events */ {123, 125, 126, 127, 128, 129, 130},
     /** text */ "Stock Market Crash Leads to Financial Turmoil and Investor Losses",
     /** duration */ 7,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 10,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -4}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 125,
     /** mutually_exclusive_events */ {124},
     /** text */ "Introduction of Blockchain Technology Enhances Security and Efficiency in Financial Transactions",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 10,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 5}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 126,
     /** mutually_exclusive_events */ {124},
     /** text */ "Digital Wallets Gain Popularity, Simplifying Payment Processes and Increasing Financial Inclusion",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 10,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 4}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 127,
     /** mutually_exclusive_events */ {124},
     /** text */ "Digital Payment Grows As Physical Cash Payment Deemed Outdated",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 10,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 4}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 128,
     /** mutually_exclusive_events */ {124},
     /** text */ "Cryptocurrency Plummets",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 10,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -30}, {upper_limit, 0}}},
    {/** event_id */ 129,
     /** mutually_exclusive_events */ {124},
     /** text */ "Cryptocurrency Skyrockets",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 10,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 5}, {lower_limit, 0}, {upper_limit, 30}}},
    {/** event_id */ 130,
     /** mutually_exclusive_events */ {124},
     /** text */ "More People Buy Insurance As Natrual Disasters Go More Common",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 10,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 2}, {lower_limit, 0}, {upper_limit, 15}}},
    // event_id 131 to 145 affect category "Food&Beverage"
    {/** event_id */ 131,
     /** mutually_exclusive_events */ {},
     /** text */ "Plant-Based Food Trend Continues to Grow, Offering Healthier and Sustainable Options",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 5}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 132,
     /** mutually_exclusive_events */ {},
     /** text */ "Food Safety Scandal Raises Concerns About Contaminated Products and Consumer Health",
     /** duration */ 7,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -4}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 133,
     /** mutually_exclusive_events */ {},
     /** text */ "Introduction of Innovative Cooking Techniques Enhances Culinary Experiences",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 4}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 134,
     /** mutually_exclusive_events */ {},
     /** text */ "Global Food Shortage Crisis Impacts Prices and Availability of Essential Commodities",
     /** duration */ 6,
     /** percentage_permille */ 15,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -7}, {lower_limit, -25}, {upper_limit, 0}}},
    {/** event_id */ 135,
     /** mutually_exclusive_events */ {},
     /** text */ "Rise of Food Delivery Services Provides Convenient and Wide-ranging Dining Options",
     /** duration */ 5,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 4}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 136,
     /** mutually_exclusive_events */ {},
     /** text */ "Growing Demand for Organic and Locally Sourced Food Drives Sustainable Farming Practices",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 5}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 137,
     /** mutually_exclusive_events */ {},
     /** text */ "Anti-desertification Releases Desert Land For Farming",
     /** duration */ 6,
     /** percentage_permille */ 7,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 3}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 138,
     /** mutually_exclusive_events */ {},
     /** text */ "Extreme Weather Strikes, Crops Die",
     /** duration */ 6,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 139,
     /** mutually_exclusive_events */ {},
     /** text */ "Mass Food Poisoning Prompts Re-Evaluation On Food Safety",
     /** duration */ 6,
     /** percentage_permille */ 5,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.19}, {mean, -5}, {lower_limit, -39}, {upper_limit, 0}}},
    {/** event_id */ 140,
     /** mutually_exclusive_events */ {},
     /** text */ "Lab-Grown Meat Can Prove A Feasible Source Of Food As Production Scales Up",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, 4}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 141,
     /** mutually_exclusive_events */ {},
     /** text */ "Global Warming Caused Famine This Summer",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.11}, {mean, -6}, {lower_limit, -10}, {upper_limit, 10}}},
    {/** event_id */ 142,
     /** mutually_exclusive_events */ {143},
     /** text */ "International Trades Of Basic Food (Rice Corn etc) High",
     /** duration */ 6,
     /** percentage_permille */ 20,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 4}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 143,
     /** mutually_exclusive_events */ {142},
     /** text */ "International Trades Of Basic Food (Rice Corn etc) Low",
     /** duration */ 6,
     /** percentage_permille */ 20,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -4}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 144,
     /** mutually_exclusive_events */ {},
     /** text */ "Population Decline Causes Food Demand Drop"
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -22}, {upper_limit, 0}}},
    {/** event_id */ 145,
     /** mutually_exclusive_events */ {},
     /** text */ "Scientists Found Way To Perform Farming Stacked In Skyscrapers"
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 11,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 25}}},
    // event_id 146 to 160 affect category "Healthcare"
    {/** event_id */ 146,
     /** mutually_exclusive_events */ {},
     /** text */ "Advancements in Telemedicine Improve Access to Medical Care for Remote Areas",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 147,
     /** mutually_exclusive_events */ {},
     /** text */ "Outbreak of Global Pandemic Leads to Overwhelmed Healthcare Systems and High Mortality Rates",
     /** duration */ 8,
     /** percentage_permille */ 15,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, 7}, {lower_limit, 0}, {upper_limit, 25}}},
    {/** event_id */ 148,
     /** mutually_exclusive_events */ {},
     /** text */ "Development of Personalized Medicine Leads to More Effective Treatment and Prevention Strategies",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 5}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 149,
     /** mutually_exclusive_events */ {},
     /** text */ "Shortage of Healthcare Professionals Causes Strain on Medical Services and Longer Wait Times",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -4}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 150,
     /** mutually_exclusive_events */ {},
     /** text */ "Advancements in Gene Editing Technology Open New Avenues for Precision Medicine",
     /** duration */ 7,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 151,
     /** mutually_exclusive_events */ {152},
     /** text */ "Government Cuts Subsidies On Public Medication",
     /** duration */ 7,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -4}, {lower_limit, -30}, {upper_limit, 0}}},
    {/** event_id */ 152,
     /** mutually_exclusive_events */ {151},
     /** text */ "Government Put More Fund In Hospitals",
     /** duration */ 7,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 4}, {lower_limit, 0}, {upper_limit, 30}}},
    {/** event_id */ 153,
     /** mutually_exclusive_events */ {},
     /** text */ "Medical Accident Prompts Stricter Standards",
     /** duration */ 7,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.13}, {mean, -5}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 154,
     /** mutually_exclusive_events */ {},
     /** text */ "Corruption Scandal Arises Within Hospitals",
     /** duration */ 7,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -7}, {lower_limit, -30}, {upper_limit, 0}}},
    {/** event_id */ 155,
     /** mutually_exclusive_events */ {},
     /** text */ "Population Aging Reaches Critical Point, Larger Amount Of People Requires Medical Attention",
     /** duration */ 7,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 7}, {lower_limit, 0}, {upper_limit, 25}}},
    {/** event_id */ 156,
     /** mutually_exclusive_events */ {},
     /** text */ "War Causes Less Medical Resources Reach Citizens",
     /** duration */ 7,
     /** percentage_permille */ 6,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -8}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 157,
     /** mutually_exclusive_events */ {},
     /** text */ "More Hospitals Were Built In Developing Countries",
     /** duration */ 7,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 23}}},
    {/** event_id */ 158,
     /** mutually_exclusive_events */ {159},
     /** text */ "New Low In Blood and Organ Donations",
     /** duration */ 7,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 3}, {lower_limit, 0}, {upper_limit, 0}}},
    {/** event_id */ 159,
     /** mutually_exclusive_events */ {158},
     /** text */ "New High In Blood and Organ Donations",
     /** duration */ 7,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -3}, {lower_limit, 0}, {upper_limit, 0}}},
    {/** event_id */ 160,
     /** mutually_exclusive_events */ {},
     /** text */ "Nuclear Leak Causes Pollution, Health Of Citizens Decline",
     /** duration */ 7,
     /** percentage_permille */ 6,
     /** type_of_event */ category,
     /** category */ 12,
     /** modifiers */ {{standard_deviation, 0.2}, {mean, +2}, {lower_limit, -10}, {upper_limit, 20}}},
    // event_id 161 to 175 affect category "Tech"
    {/** event_id */ 161,
     /** mutually_exclusive_events */ {169, 171},
     /** text */ "Breakthrough in Artificial Intelligence Leads to Significant Advancements in Automation and Machine Learning",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 162,
     /** mutually_exclusive_events */ {},
     /** text */ "Cybersecurity Breach Exposes Sensitive Data and Raises Concerns Over Digital Privacy",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 163,
     /** mutually_exclusive_events */ {},
     /** text */ "Emergence of 5G Technology Revolutionizes Connectivity and Enables Faster Data Transfer",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 5}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 164,
     /** mutually_exclusive_events */ {},
     /** text */ "Failure of Major Tech Infrastructure Disrupts Services and Causes Widespread Outages",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -4}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 165,
     /** mutually_exclusive_events */ {},
     /** text */ "Advancements in Quantum Computing Unlock New Possibilities for Solving Complex Problems",
     /** duration */ 7,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 166,
     /** mutually_exclusive_events */ {},
     /** text */ "Rapid Advancements in Augmented Reality (AR) and Virtual Reality (VR) Enhance User Experiences",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 5}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 167,
     /** mutually_exclusive_events */ {},
     /** text */ "Advancements in Robotics and Automation Transform Manufacturing and Increase Efficiency",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 168,
     /** mutually_exclusive_events */ {169, 171},
     /** text */ "Emergence of Artificial General Intelligence (AGI) Raises Ethical and Societal Concerns",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 169,
     /** mutually_exclusive_events */ {161, 168, 170, 171},
     /** text */ "Artificial Intelligence Development Plateus As Calculation Power Prove Insufficent",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -3}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 170,
     /** mutually_exclusive_events */ {169, 173},
     /** text */ "New Semiconductor 100 Times More Powerful Than Silicon Arises, CPU Power Skyrockets",
     /** duration */ 7,
     /** percentage_permille */ 8,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.14}, {mean, 7}, {lower_limit, -5}, {upper_limit, 50}}},
    {/** event_id */ 171,
     /** mutually_exclusive_events */ {161, 168, 169},
     /** text */ "Artificial Intelligence Development Halted And Banned Due To Concerns By Specialists",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -8}, {lower_limit, -30}, {upper_limit, 0}}},
    {/** event_id */ 172,
     /** mutually_exclusive_events */ {},
     /** text */ "Undecodable Quantum Encryption Commercializes",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, 5}, {lower_limit, 0}, {upper_limit, 25}}},
    {/** event_id */ 173,
     /** mutually_exclusive_events */ {170},
     /** text */ "Returns In Development Of Processors Diminish As Silicon Transistor Reach Fundamental Limit",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 174,
     /** mutually_exclusive_events */ {},
     /** text */ "Human-Machine Link Project Halted Due To Ethical Concerns",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -25}, {upper_limit, 0}}},
    {/** event_id */ 175,
     /** mutually_exclusive_events */ {},
     /** text */ "Satelite Communication Reaches Speeds As Fast As 5G",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 13,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 20}}},
    // event_id 176 to 187 affect category "RealEstate"
    {/** event_id */ 176,
     /** mutually_exclusive_events */ {177},
     /** text */ "Strong Demand and Low Mortgage Rates Drive Real Estate Market Growth",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 14,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 5}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 177,
     /** mutually_exclusive_events */ {176},
     /** text */ "Economic Downturn Leads to Decline in Real Estate Prices and Sales",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 14,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 178,
     /** mutually_exclusive_events */ {},
     /** text */ "Rapid Urbanization and Infrastructure Development Boost Real Estate Investments",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 14,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 179,
     /** mutually_exclusive_events */ {},
     /** text */ "Natural Disasters Cause Property Damage and Impact Real Estate Market",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 14,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 180,
     /** mutually_exclusive_events */ {},
     /** text */ "Investigation Reveals Widespread Cases of Substandard Construction Projects",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 14,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -4}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 181,
     /** mutually_exclusive_events */ {},
     /** text */ "Estate Development Companies Bankrupt, Hundreds Of Buildings Unfinished",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 14,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -8}, {lower_limit, -40}, {upper_limit, 0}}},
    {/** event_id */ 182,
     /** mutually_exclusive_events */ {183},
     /** text */ "Government Accelerates Public Estate Construction, Private Estate Face Competition",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 14,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -4}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 183,
     /** mutually_exclusive_events */ {182},
     /** text */ "Government Delays Public Estate Construction, Private Estate Stand Uncompeted",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 14,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, 4}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 184,
     /** mutually_exclusive_events */ {185},
     /** text */ "Government Increase Taxes For Non-Residing External Investors In Real Estate",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 14,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, -3}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 185,
     /** mutually_exclusive_events */ {184},
     /** text */ "Government Decrease Taxes For Non-Residing External Investors In Real Estate",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 14,
     /** modifiers */ {{standard_deviation, 0.12}, {mean, 3}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 186,
     /** mutually_exclusive_events */ {187},
     /** text */ "Net Migrations Are Going Out The Region, Residence Needs Fall",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 14,
     /** modifiers */ {{standard_deviation, 0.11}, {mean, -2}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 187,
     /** mutually_exclusive_events */ {186},
     /** text */ "Net Migrations Are Going In The Region, Residence Needs Rise",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 14,
     /** modifiers */ {{standard_deviation, 0.11}, {mean, 2}, {
                                                                  lower_limit,
                                                              },
                       {upper_limit, 15}}},
    // event_id 188 to 193 affect category "Retail"
    {/** event_id */ 188,
     /** mutually_exclusive_events */ {},
     /** text */ "Shift in Consumer Behavior Leads to Decline in Brick-and-Mortar Retail Stores",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 15,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 189,
     /** mutually_exclusive_events */ {},
     /** text */ "Adoption of Technology Enhances Customer Experience in Physical Retail Stores",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 15,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 190,
     /** mutually_exclusive_events */ {},
     /** text */ "Integration of Augmented Reality Enhances In-Store Shopping Experience",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 15,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 5}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 191,
     /** mutually_exclusive_events */ {},
     /** text */ "Increase in Online Counterfeit Products Impacts Consumer Trust in E-commerce",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 15,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 192,
     /** mutually_exclusive_events */ {},
     /** text */ "Retailers Embrace Sustainable Practices, Driving Eco-friendly Consumer Choices",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 15,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 193,
     /** mutually_exclusive_events */ {},
     /** text */ "Supply Chain Disruptions Impact Retail Inventory and Availability",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 15,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -15}, {upper_limit, 0}}},
    // event_id 194 to 201 affect category "Telecom"
    {/** event_id */ 194,
     /** mutually_exclusive_events */ {},
     /** text */ "Deployment of 5G Networks Enables Faster and More Reliable Connectivity",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 16,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 5}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 195,
     /** mutually_exclusive_events */ {},
     /** text */ "Cybersecurity Breach in Telecom Networks Raises Concerns over Data Privacy",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 16,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 196,
     /** mutually_exclusive_events */ {},
     /** text */ "Advancements in Voice Recognition Technology Enhance Telecommunication Services",
     /** duration */ 6,
     /** percentage_permille */ 12,
     /** type_of_event */ category,
     /** category */ 16,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 197,
     /** mutually_exclusive_events */ {},
     /** text */ "Network Outage Disrupts Telecommunication Services in Several Regions",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 16,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 198,
     /** mutually_exclusive_events */ {},
     /** text */ "Telecom Service Outage Caused by Natural Disaster Disrupts Communication",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 16,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 199,
     /** mutually_exclusive_events */ {},
     /** text */ "Telecom Regulatory Changes Affect Pricing and Service Plans for Consumers",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 16,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -5}, {lower_limit, -15}, {upper_limit, 0}}},
    {/** event_id */ 200,
     /** mutually_exclusive_events */ {},
     /** text */ "Rumors About 6G Been Optimistic: Strong and Reliable Enough For Over-The-Air Autonomous Driving",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 16,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, 6}, {lower_limit, 0}, {upper_limit, 20}}},
    {/** event_id */ 201,
     /** mutually_exclusive_events */ {},
     /** text */ "Government Forces Reduction Of Data Price As Phone Data Grows To Become Essential",
     /** duration */ 7,
     /** percentage_permille */ 10,
     /** type_of_event */ category,
     /** category */ 16,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -4}, {lower_limit, -15}, {upper_limit, 0}}},
    // event_id 202 to 209 affect pick_random_stock
    {/** event_id */ 202,
     /** mutually_exclusive_events */ {},
     /** text */ "Leadership Change: CEO Resigns, New CEO Appointed",
     /** duration */ 3,
     /** percentage_permille */ 10,
     /** type_of_event */ pick_random_stock,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.2}, {mean, 0}, {lower_limit, -15}, {upper_limit, 15}}},
    {/** event_id */ 203,
     /** mutually_exclusive_events */ {},
     /** text */ "Labor Strike: Employees Go on Strike Demanding Better Working Conditions",
     /** duration */ 3,
     /** percentage_permille */ 12,
     /** type_of_event */ pick_random_stock,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -6}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 204,
     /** mutually_exclusive_events */ {207},
     /** text */ "Acquires a Competitor, Expands Market Presence",
     /** duration */ 4,
     /** percentage_permille */ 10,
     /** type_of_event */ pick_random_stock,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.2}, {mean, 5}, {lower_limit, 0}, {upper_limit, 15}}},
    {/** event_id */ 205,
     /** mutually_exclusive_events */ {209},
     /** text */ "Market Slump Leads to Business Contraction",
     /** duration */ 4,
     /** percentage_permille */ 10,
     /** type_of_event */ pick_random_stock,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.3}, {mean, -7}, {lower_limit, -20}, {upper_limit, 0}}},
    {/** event_id */ 206,
     /** mutually_exclusive_events */ {207},
     /** text */ "Regulatory Non-Compliance: Fails to Meet Environmental Standards",
     /** duration */ 5,
     /** percentage_permille */ 10,
     /** type_of_event */ pick_random_stock,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.1}, {mean, -2}, {lower_limit, -10}, {upper_limit, 0}}},
    {/** event_id */ 207,
     /** mutually_exclusive_events */ {202, 203, 204, 206, 208, 209},
     /** text */ "Faces Bankruptcy, Forced to Cease Operations",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ pick_random_stock,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.5}, {mean, -9}, {lower_limit, -30}, {upper_limit, 0}}},
    {/** event_id */ 208,
     /** mutually_exclusive_events */ {207},
     /** text */ "Company Was Accquired By Another, All Investors Now Have The Shares Of The Accquiring Company",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ pick_random_stock,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.6}, {mean, 0}, {lower_limit, -50}, {upper_limit, 50}}},
    {/** event_id */ 209,
     /** mutually_exclusive_events */ {207, 205},
     /** text */ "Opens New Branches in Multiple Locations",
     /** duration */ 6,
     /** percentage_permille */ 10,
     /** type_of_event */ pick_random_stock,
     /** category */ 0,
     /** modifiers */ {{standard_deviation, 0.5}, {mean, 7}, {lower_limit, 0}, {upper_limit, 20}}}};

// print a map
void print_map(std::map<unsigned int, std::vector<unsigned int>> map) {
    for (auto i : map) {
        std::cout << i.first << ": ";
        for (unsigned int j : i.second) {
            std::cout << j << " ";
        }
        std::cout << std::endl;
    }
}

/*
int main() {
    // This outputs 0.1
    std::cout << all_stock_events[0].modifiers[standard_deviation] << std::endl;
    // Checks the events for mutual exclusivity
    print_map(check_mutual_exclusivity(all_stock_events));
    // Outputs:
    // 0: 2
    // 1: 2
    // 2:
    return 0;
}
*/

std::map<unsigned int, std::vector<unsigned int>> check_mutual_exclusivity(std::vector<Stock_event> all_events) {
    std::map<unsigned int, std::vector<unsigned int>> mut_excl_map;
    // Build the map
    for (unsigned int i = 0; i < all_events.size(); i++) {
        for (unsigned int j = 0; j < all_events[i].mutually_exclusive_events.size(); j++) {
            mut_excl_map[all_events[i].event_id].push_back(all_events[i].mutually_exclusive_events[j]);
        }
    }
    // If two events are mutually exclusive, they should be in each other's list.
    // Remove such two events from the map.
    // E.g. {0: [1,2], 1: [0], 2:[]} -> {0: [2]}
    // In this case, 2 does not state that it is mutually exclusive with 0.
    for (auto i : mut_excl_map) {
        for (unsigned int j : i.second) {
            if (std::find(mut_excl_map[j].begin(), mut_excl_map[j].end(), i.first) != mut_excl_map[j].end()) {
                mut_excl_map[i.first].erase(std::remove(mut_excl_map[i.first].begin(), mut_excl_map[i.first].end(), j), mut_excl_map[i.first].end());
                mut_excl_map[j].erase(std::remove(mut_excl_map[j].begin(), mut_excl_map[j].end(), i.first), mut_excl_map[j].end());
            }
        }
    }
    return mut_excl_map;
}

std::vector<Stock_event> pick_events(std::vector<Stock_event> all_events, unsigned int num_events) {
    std::vector<Stock_event> picked_events;
    // Pick num_events random events
    for (unsigned int i = 0; i < num_events; i++) {
        // When picking the event, consider event.probability_permille.
        unsigned int total_permille = 0;
        for (Stock_event event : all_events) {
            total_permille += event.probability_permille;
        }
        /** E.g. if there are 3 events with probability_permille 10, 20, 30.
         * total_permille = 60;
         * random_permille = 0 to 59;
         * If random_permille is 0 to 9, pick the first event;
         * If random_permille is 10 to 29, pick the second event;
         * If random_permille is 30 to 59, pick the third event.
         */
        unsigned int random_permille = rand() % total_permille;
        for (Stock_event event : all_events) {
            total_permille -= event.probability_permille;
            if (total_permille <= random_permille) {
                picked_events.push_back(event);
                break;
            }
        }
    }
    // Check event duplication and mutual exclusivity
    std::map<unsigned int, std::vector<unsigned int>> mut_excl_map = check_mutual_exclusivity(all_events);
    for (unsigned int i = 0; i < picked_events.size(); i++) {
        for (unsigned int j = i + 1; j < picked_events.size(); j++) {
            // If two events are the same, remove one of them
            // Note that we don't remove the duplicate events with type_of_event == pick_random_stock
            if (picked_events[i].event_id == picked_events[j].event_id &&
                picked_events[i].type_of_event != pick_random_stock) {
                picked_events.erase(picked_events.begin() + j);
                j--;
            }
            // If two events are mutually exclusive, remove one of them
            else if (std::find(mut_excl_map[picked_events[i].event_id].begin(), mut_excl_map[picked_events[i].event_id].end(), picked_events[j].event_id) != mut_excl_map[picked_events[i].event_id].end()) {
                picked_events.erase(picked_events.begin() + j);
                j--;
            }
        }
    }
    return picked_events;
}
